apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-uavlecbh
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-uavlecbh:6a25f39942b00fb4190f34398bf007fbee708f71@sha256:6023c48837e3ca04b5bce631790a6d6fb523d65817ccef42c22ef3be2aa6325f
          name: container-image
